spring.application.name=backend

# ===============================
# DATABASE CONFIG
# ===============================

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/xp_up}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:dml231200...}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# JWT
# ===============================
app.jwt.secret=${JWT_SECRET:MiClaveSuperSecretaParaXPUp2026MiClaveSuperSecretaParaXPUp2026}
app.jwt.expiration-ms=86400000

# ===============================
# RAWG
# ===============================
rawg.api.key=${RAWG_API_KEY:8d707d272cd34f2393cab33fec4880d5}
rawg.api.base-url=https://api.rawg.io/api